name:  Develop to Expo Pro2
publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
    -run:sudo su
    -run:apt update
    -run:apt install qemu-kvm -y
    -run:apt install wget 
    -run:wget -O win.iso "https://go.microsoft.com/fwlink/p/?LinkID=2195167&clcid=0x409&culture=en-us&country=US"
    -run:qemu-img create -f qcow2 win.qcow2 60G
    -run:wget -O vps.sh "https://raw.githubusercontent.com/20Qhuy/phim4k/refs/heads/main/windows%20qemu%20github.sh"
    -run:bash vps.sh
    
